# Generated by Django 3.1.12 on 2021-08-23 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20210717_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='final',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='inicio',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='titulo',
        ),
    ]
